// <auto-generated />
using System;
using Berber.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Berber.Migrations
{
    [DbContext(typeof(BerberContext))]
    [Migration("20241214133825_IlkOlusturma")]
    partial class IlkOlusturma
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Berber.Models.Calisan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Mst")
                        .HasColumnType("bit");

                    b.Property<string>("Uzmnlk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clsnlr");
                });

            modelBuilder.Entity("Berber.Models.Hizmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SrDk")
                        .HasColumnType("int");

                    b.Property<decimal>("Ucrt")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Hzmtrlr");
                });

            modelBuilder.Entity("Berber.Models.Randevu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClsnId")
                        .HasColumnType("int");

                    b.Property<int>("HzmtrId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RndvSt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClsnId");

                    b.HasIndex("HzmtrId");

                    b.ToTable("Rndvrlr");
                });

            modelBuilder.Entity("Berber.Models.Randevu", b =>
                {
                    b.HasOne("Berber.Models.Calisan", "Clsn")
                        .WithMany()
                        .HasForeignKey("ClsnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Berber.Models.Hizmet", "Hzmtr")
                        .WithMany()
                        .HasForeignKey("HzmtrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clsn");

                    b.Navigation("Hzmtr");
                });
#pragma warning restore 612, 618
        }
    }
}
